/**
 * sync-config.ts — reads parent repo config files and writes src/config/generated.ts.
 *
 * Runs as `predev` and `prebuild` npm hooks. This is the ONLY file that
 * references anything outside frontend/. When extracting the frontend as a
 * standalone repo, replace generated.ts with hand-written values.
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "../.."); // orderbook/
const outPath = resolve(__dirname, "../src/config/generated.ts");

function readEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  const lines = readFileSync(path, "utf-8").split("\n");
  const env: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let value = trimmed.slice(eqIdx + 1).trim();
    // Strip surrounding quotes.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

// Read extension.env
const extensionEnv = readEnvFile(resolve(root, "config/extension.env"));
const extensionId = extensionEnv["EXTENSION_ID"] || "";
const instructionSender = extensionEnv["INSTRUCTION_SENDER"] || "";

// Read test-tokens.env
const tokensEnv = readEnvFile(resolve(root, "config/test-tokens.env"));
const baseToken = tokensEnv["BASE_TOKEN"] || "";
const quoteToken = tokensEnv["QUOTE_TOKEN"] || "";

// Read pairs.json
let pairs: Array<{ name: string; baseToken: string; quoteToken: string }> = [];
const pairsPath = resolve(root, "config/pairs.json");
if (existsSync(pairsPath)) {
  pairs = JSON.parse(readFileSync(pairsPath, "utf-8"));
}

// Read OrderbookInstructionSender ABI
let instructionSenderAbi: unknown[] = [];
const abiPath = resolve(
  root,
  "out/InstructionSender.sol/OrderbookInstructionSender.json"
);
if (existsSync(abiPath)) {
  const artifact = JSON.parse(readFileSync(abiPath, "utf-8"));
  instructionSenderAbi = artifact.abi;
}

const output = `// AUTO-GENERATED by scripts/sync-config.ts — do not edit manually.
// Re-run: npm run sync-config

export const EXTENSION_ID = "${extensionId}";

export const INSTRUCTION_SENDER = "${instructionSender}" as \`0x\${string}\`;

export const BASE_TOKEN = "${baseToken}" as \`0x\${string}\`;

export const QUOTE_TOKEN = "${quoteToken}" as \`0x\${string}\`;

export interface PairConfig {
  name: string;
  baseToken: string;
  quoteToken: string;
}

export const PAIRS: PairConfig[] = ${JSON.stringify(pairs, null, 2)};

export const INSTRUCTION_SENDER_ABI: unknown[] = ${JSON.stringify(instructionSenderAbi, null, 2)};
`;

writeFileSync(outPath, output, "utf-8");
console.log(`[sync-config] wrote ${outPath}`);
