// AUTO-GENERATED by scripts/sync-config.ts — do not edit manually.
// Re-run: npm run sync-config

export const EXTENSION_ID = "0x00000000000000000000000000000000000000000000000000000000000005f1";

export const INSTRUCTION_SENDER = "0x01039A0c039067ad80E3a179dF7C14C6d5E61A4f" as `0x${string}`;

export const BASE_TOKEN = "0xcF6F4cB8c983d623C9E5947fD9d37cAdD4aaE9C1" as `0x${string}`;

export const QUOTE_TOKEN = "0x3635Cb375fb0fbdFad888874064d3D5e3D4aA585" as `0x${string}`;

export interface PairConfig {
  name: string;
  baseToken: string;
  quoteToken: string;
}

export const PAIRS: PairConfig[] = [
  {
    "name": "FLR/USDT",
    "baseToken": "0xcF6F4cB8c983d623C9E5947fD9d37cAdD4aaE9C1",
    "quoteToken": "0x3635Cb375fb0fbdFad888874064d3D5e3D4aA585"
  },
  {
    "name": "BTC/USDT",
    "baseToken": "0x8446025e4b00dE11dF56aaEC05b72b71d025D3f7",
    "quoteToken": "0x3635Cb375fb0fbdFad888874064d3D5e3D4aA585"
  },
  {
    "name": "ETH/USDT",
    "baseToken": "0x013d47B383F2630B9BD7151b82915CB7EAd31D0A",
    "quoteToken": "0x3635Cb375fb0fbdFad888874064d3D5e3D4aA585"
  }
];

export const INSTRUCTION_SENDER_ABI: unknown[] = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_teeExtensionRegistry",
        "type": "address",
        "internalType": "contract ITeeExtensionRegistry"
      },
      {
        "name": "_teeMachineRegistry",
        "type": "address",
        "internalType": "contract ITeeMachineRegistry"
      },
      {
        "name": "_admins",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "OP_COMMAND_DEPOSIT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "OP_COMMAND_WITHDRAW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "OP_TYPE_ORDERBOOK",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TEE_EXTENSION_REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ITeeExtensionRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TEE_MACHINE_REGISTRY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ITeeMachineRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admins",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "allowUser",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "allowed",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deposit",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "executeWithdrawal",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "withdrawalId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "kycEnabled",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "removeUser",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setExtensionId",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setKycEnabled",
    "inputs": [
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTeeAddress",
    "inputs": [
      {
        "name": "_teeAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "teeAddress",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "teeAddressSet",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "usedWithdrawalIds",
    "inputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  }
];
