#!/usr/bin/env bash
# test.sh — Send instructions on-chain, poll for results, and validate correctness.
#
# Run this AFTER post-build.sh (TEE machine must be registered and running).
#
# Inputs (env vars):
#   EXT_PROXY_URL       — extension proxy URL (default: http://localhost:6674)
#   CHAIN_URL           — chain RPC URL (default: http://127.0.0.1:8545)
#   ADDRESSES_FILE      — path to deployed-addresses.json (auto-detected if unset)
#   INSTRUCTION_SENDER  — deployed InstructionSender address (from config/extension.env)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[test]${NC} $*"; }
step() { echo -e "\n${CYAN}=== Step $1: $2 ===${NC}"; }
die()  { echo -e "${RED}[test] ERROR:${NC} $*" >&2; exit 1; }

# --- Load .env from project root (if present) ---
if [[ -f "$PROJECT_DIR/.env" ]]; then
    set -a
    source "$PROJECT_DIR/.env"
    set +a
fi

# --- Source extension config (generated by pre-build.sh) ---
CONFIG_FILE="$PROJECT_DIR/config/extension.env"
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
    log "Loaded config from $CONFIG_FILE"
fi

EXT_PROXY_URL="${EXT_PROXY_URL:-http://localhost:6674}"
CHAIN_URL="${CHAIN_URL:-http://127.0.0.1:8545}"
ADDRESSES_FILE="${ADDRESSES_FILE:-}"
INSTRUCTION_SENDER="${INSTRUCTION_SENDER:-}"

[[ -n "$INSTRUCTION_SENDER" ]] || die "INSTRUCTION_SENDER not set. Run pre-build.sh first or set it manually."

# --- Auto-detect addresses file ---
if [[ -z "$ADDRESSES_FILE" ]]; then
    for candidate in \
        "$PROJECT_DIR/../../e2e/docker/sim_dump/deployed-addresses.json" \
        "$PROJECT_DIR/../docker/sim_dump/deployed-addresses.json" \
        "$PROJECT_DIR/../../docker/sim_dump/deployed-addresses.json" \
        "$PROJECT_DIR/../../../docker/sim_dump/deployed-addresses.json"; do
        if [[ -f "$candidate" ]]; then
            ADDRESSES_FILE="$(cd "$(dirname "$candidate")" && pwd)/$(basename "$candidate")"
            break
        fi
    done
    [[ -n "$ADDRESSES_FILE" ]] || die "Cannot find deployed-addresses.json. Set ADDRESSES_FILE."
fi

[[ -f "$ADDRESSES_FILE" ]] || die "Addresses file not found: $ADDRESSES_FILE"

log "Extension proxy:    $EXT_PROXY_URL"
log "Chain URL:          $CHAIN_URL"
log "Addresses file:     $ADDRESSES_FILE"
log "InstructionSender:  $INSTRUCTION_SENDER"

# --- Pre-flight: verify extension proxy is reachable ---
if ! curl -sf -o /dev/null "$EXT_PROXY_URL/info" 2>/dev/null; then
    die "Extension proxy not reachable at $EXT_PROXY_URL. Is Docker Compose running? (docker compose up -d)"
fi
log "Extension proxy is reachable"

# --- Run test ---
step 1 "Run extension tests"
cd "$PROJECT_DIR/tools"
go run ./cmd/run-test \
    -a "$ADDRESSES_FILE" \
    -c "$CHAIN_URL" \
    -p "$EXT_PROXY_URL" \
    -instructionSender "$INSTRUCTION_SENDER" \
    || die "Test failed"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN} Tests passed${NC}"
echo -e "${GREEN}========================================${NC}"
